// rules.ts
export const categoryRules: Record<string, string> = {
  // Groceries
  "whole foods": "Groceries",
  "trader joe": "Groceries",
  "costco": "Groceries",
  "walmart": "Groceries",
  "safeway": "Groceries",
  "kroger": "Groceries",
  "aldi": "Groceries",
  "grocery": "Groceries",
  "target": "Groceries",
  "food lion": "Groceries",
  "winco": "Groceries",

  // Restaurants / Dining
  "starbucks": "Dining",
  "mcdonald": "Dining",
  "burger king": "Dining",
  "chipotle": "Dining",
  "subway": "Dining",
  "panera": "Dining",
  "dominos": "Dining",
  "pizza hut": "Dining",
  "taco bell": "Dining",
  "restaurant": "Dining",
  "cafe": "Dining",
  "coffee": "Dining",
  "dining": "Dining",
  "kfc": "Dining",
  "wendys": "Dining",

  // Utilities / Bills
  "verizon": "Utilities",
  "comcast": "Utilities",
  "att": "Utilities",
  "spectrum": "Utilities",
  "electric": "Utilities",
  "water": "Utilities",
  "gas": "Utilities",
  "utility": "Utilities",
  "seattle city light": "Utilities",
  "pg&e": "Utilities",
  "con edison": "Utilities",
  "rocket": "Utilities",

  // Subscriptions / Software
  "netflix": "Subscriptions",
  "spotify": "Subscriptions",
  "hulu": "Subscriptions",
  "prime": "Subscriptions",
  "adobe": "Subscriptions",
  "dropbox": "Subscriptions",
  "subscription": "Subscriptions",
  "discord": "Subscriptions",
  "slack": "Subscriptions",
  "notion": "Subscriptions",
  "figma": "Subscriptions",

  // Transportation / Travel
  "uber": "Transportation",
  "lyft": "Transportation",
  "shell": "Transportation",
  "chevron": "Transportation",
  "exxon": "Transportation",
  "gas station": "Transportation",
  "bus": "Transportation",
  "train": "Transportation",
  "amtrak": "Transportation",
  "delta": "Travel",
  "southwest": "Travel",
  "airbnb": "Travel",
  "marriott": "Travel",
  "hilton": "Travel",
  "booking.com": "Travel",
  "uber eats": "Dining",
  "grubhub": "Dining",

  // Shopping / Retail
  "amazon": "Shopping",
  "best buy": "Shopping",
  "macy": "Shopping",
  "shopping": "Shopping",
  "ebay": "Shopping",
  "etsy": "Shopping",
  "homedepot": "Shopping",
  "lowes": "Shopping",
  "ikea": "Shopping",

  // Health / Fitness
  "gym": "Health & Fitness",
  "planet fitness": "Health & Fitness",
  "medical": "Health & Fitness",
  "pharmacy": "Health & Fitness",
  "walgreens": "Health & Fitness",
  "cvs": "Health & Fitness",
  "fitness": "Health & Fitness",
  "doctor": "Health & Fitness",
  "dentist": "Health & Fitness",
  "chiropractic": "Health & Fitness",
  "yoga": "Health & Fitness",
  "pilates": "Health & Fitness",

  // Entertainment / Fun
  "movie": "Entertainment",
  "cinema": "Entertainment",
  "amc": "Entertainment",
  "concert": "Entertainment",
  "theater": "Entertainment",
  "zoo": "Entertainment",
  "museum": "Entertainment",
  "amusement": "Entertainment",
  "game": "Entertainment",
  "stadium": "Entertainment",

  // Banking / Financial
  "atm": "Banking",
  "deposit": "Banking",
  "payment": "Banking",
  "transfer": "Banking",
  "interest": "Banking",
  "fee": "Banking",
  "credit card": "Banking",
  "withdrawal": "Banking",
  "paypal": "Banking",
  "venmo": "Banking",
  "square": "Banking",
  "check": "Banking",

  // Housing / Rent
  "rent": "Housing",
  "mortgage": "Housing",
  "landlord": "Housing",
  "apartment": "Housing",
  "homeowner": "Housing",
  "hoa": "Housing",
  "lease": "Housing",

  // Insurance
  "insurance": "Insurance",
  "geico": "Insurance",
  "progressive": "Insurance",
  "state farm": "Insurance",
  "health insurance": "Insurance",
  "car insurance": "Insurance",

  // Education / Learning
  "udemy": "Education",
  "coursera": "Education",
  "school": "Education",
  "tuition": "Education",
  "bookstore": "Education",
  "college": "Education",
  "university": "Education",
  "class": "Education",
  "course": "Education",

  // Taxes / Government
  "irs": "Taxes",
  "tax": "Taxes",
  "property tax": "Taxes",
  "city tax": "Taxes",
  "state tax": "Taxes",
  "federal tax": "Taxes",
  "municipal": "Taxes",

  // Donations / Charity
  "charity": "Donations",
  "donation": "Donations",
  "ngo": "Donations",
  "red cross": "Donations",
  "salvation army": "Donations",
  "fundraiser": "Donations",

  // Miscellaneous / Other
  "misc": "Miscellaneous",
  "unknown": "Miscellaneous",
  "other": "Miscellaneous",
  "service charge": "Miscellaneous",
  "cash": "Miscellaneous",
  "gift": "Miscellaneous",
};
